### ISSUE TITLE
FEATURE: Select a group of files within the folder

### ISSUE THREAD

**Issue by grabani** [buimanhtoan-it/combine-code-in-folder#1]
Hi There,

This is a very useful extension, however, it would greatly benefit from having the ability to select individual files and have them copied to the clipboard with the file name. Currently if you select several files and copy them with their file name it only copies the content of the first file highlighted;.

Thanks.

**Comment by buimanhtoan-it** [comment]
Hi @grabani,
Thank you for your suggestion. The feature you need will be available from version 1.3.2 onwards. 
Let's have a coffee together!

**Comment by grabani** [comment]
Great to hear. For What it's worth, my thoughts are:

1) To select multiple `consecutive` files the user can click on the **First** file press and hold down the SHIFT key and then click on the **Last** consecutive file.

2) To select multiple `individual` files the user can click on the **First** file press and hold down the CTRL key and then click on all of the individual files for which the contents need to be copied.

In each case the filename of the selected files should be copied followed by the contents.

Love to hear what other features you have in mind. 

Thanks.

**Comment by buimanhtoan-it** [comment]
@grabani 
I think version 1.3.2 has covered the use cases you mentioned. 
Could you please test with the new version and let me know if these features work well on your end?

**Comment by grabani** [comment]
Hi There - yes seem to work fine. Thank you for this. Great help when you are using an LLM.

PS - I can't resist. It would be great if the filenames captured could be proceed with THREE "/" (forward slashes) rather than two to differentiate them from usual comments. Also, if there could be at least a line separating the filename from the code that would be perfect. 

Thanks again.

**Comment by buimanhtoan-it** [comment]
@grabani 
I think we have a few specific cases where we use triple-slash like https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html. 
Therefore, I think keeping double slash to treat it as a regular comment will avoid affecting other use cases.

**Comment by grabani** [comment]
Thank you for all of your efforts they are greatly appreciated.

Would love to hear your thoughts on what are your plans for this extension. Happy to test any new functionality features you develop.

Take care.

**Comment by grabani** [comment]
Hi ya,

Just using you extension...

Would you be open to having your extension work with `individual files` that are open in the Editor rather than ONLY working with folders and files opened using "Open Folder"?

**Comment by buimanhtoan-it** [comment]
@grabani 
My intention in designing this extension is that it will be compact, convenient, and won’t flood the IDE with too much load for the user, as we already have too many other extensions. 
If you have a scenario where you cannot use/open the explorer to right-click (then copy), we may need to create a separate copy feature for each file. 
Can you share your thoughts?

**Comment by grabani** [comment]
Hi ya
Ultimately I think a separate copy feature for each file is the required solution for maximum flexibility (and therefore efficiency).
